# Generated by Django 3.1.5 on 2021-01-30 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beer_type', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Brewery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Beer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ibu', models.IntegerField(blank=True, null=True)),
                ('abv', models.FloatField(blank=True, null=True)),
                ('beer_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='beers.beertype')),
                ('brewery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beers.brewery')),
            ],
        ),
    ]
